apiVersion: v1
kind: Secret
metadata:
  name: app-prometheus-objstore-secret
  namespace: monitoring
stringData:
  objstore.yml: |
    type: S3
    config:
      bucket: thanos-uat
      endpoint: s3.amazonaws.com
      region: <AWS_REGION>
