apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-eso-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/iahmad-khan/infrastructure-as-code
    targetRevision: HEAD
    path: vault-eso/argocd/apps
    helm:
      valueFiles:
        - ../environments/prod/values.yaml
        - ../app-versions-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
