apiVersion: v1
kind: Service
metadata:
  name: app-prometheus-thanos-discovery
  namespace: monitoring
  labels:
    app.kubernetes.io/name: app-prometheus
spec:
  ports:
    - name: grpc
      port: 10901
      targetPort: grpc
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: app-prometheus
  clusterIP: None
