objstoreConfig: |
  type: S3
  config:
    bucket: thanos-uat
    endpoint: s3.amazonaws.com
    region: <AWS_REGION>

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<UAT_AWS_ACCOUNT_ID>:role/thanos-uat
