replicaCount: 1

image:
  repository: "your-registry/hello-world"
  tag: "uat"

ingress:
  enabled: true
  host: "hello-world.uat.<YOUR_DOMAIN>"

vault:
  secretPath: "hello-world"
  refreshInterval: "1h"
