repoURL: https://github.com/iahmad-khan/infrastructure-as-code
targetRevision: HEAD
argoCDNamespace: argocd

# Overridden per environment
env: placeholder

apps:
  eso:
    enabled: true
    syncWave: "0"
    chartVersion: "0.9.13"
    namespace: external-secrets

  vault:
    enabled: true
    syncWave: "0"
    chartVersion: "0.30.1"
    namespace: vault

  vaultConfig:
    enabled: true
    syncWave: "1"
    namespace: vault

  esoSecretstore:
    enabled: true
    syncWave: "2"
    namespace: external-secrets

  vaultMonitoring:
    enabled: true
    syncWave: "3"
    namespace: vault

  esoMonitoring:
    enabled: true
    syncWave: "3"
    namespace: external-secrets

  langfuse:
    enabled: true
    syncWave: "3"
    chartVersion: "1.3.1"
    namespace: langfuse

  helloWorld:
    enabled: true
    syncWave: "4"
    namespace: hello-world
    imageTag: "latest"

  monitoring:
    enabled: true
    syncWave: "0"
    chartVersion: "67.5.0"
    namespace: monitoring

  thanos:
    enabled: true
    syncWave: "1"
    chartVersion: "15.7.0"
    namespace: monitoring

  appPrometheus:
    enabled: true
    syncWave: "1"
    namespace: monitoring

  k8sMonitoring:
    enabled: true
    syncWave: "3"
    namespace: monitoring

  certManager:
    enabled: true
    syncWave: "0"
    chartVersion: "v1.14.5"
    namespace: cert-manager

  certManagerIssuers:
    enabled: true
    syncWave: "1"
    namespace: cert-manager

  externalDns:
    enabled: true
    syncWave: "0"
    chartVersion: "1.14.4"
    namespace: external-dns

  envoyGateway:
    enabled: true
    syncWave: "0"
    chartVersion: "v1.2.3"
    namespace: envoy-gateway-system

  envoyGatewayConfig:
    enabled: true
    syncWave: "1"
    namespace: envoy-gateway-system
