{{- if .Values.apps.esoSecretstore.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-secretstore-{{ .Values.env }}
  namespace: {{ .Values.argoCDNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.apps.esoSecretstore.syncWave | quote }}
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: vault-eso/app-default-values/eso/secretstore
    directory:
      include: "{{ .Values.env }}.yaml"
  destination:
    name: {{ .Values.env }}
    namespace: {{ .Values.apps.esoSecretstore.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
{{- end }}
