{{- if .Values.apps.helloWorld.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-{{ .Values.env }}
  namespace: {{ .Values.argoCDNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.apps.helloWorld.syncWave | quote }}
spec:
  project: default
  sources:
    - repoURL: {{ .Values.repoURL }}
      targetRevision: {{ .Values.targetRevision }}
      path: vault-eso/helm-charts/hello-world
      helm:
        parameters:
          - name: image.tag
            value: {{ .Values.apps.helloWorld.imageTag | quote }}
        valueFiles:
          - values.yaml
          - $values/vault-eso/argocd/environments/{{ .Values.env }}/hello-world/values.yaml
    - repoURL: {{ .Values.repoURL }}
      targetRevision: {{ .Values.targetRevision }}
      ref: values
  destination:
    name: {{ .Values.env }}
    namespace: {{ .Values.apps.helloWorld.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
