{{- if .Values.apps.vaultMonitoring.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-monitoring-{{ .Values.env }}
  namespace: {{ .Values.argoCDNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.apps.vaultMonitoring.syncWave | quote }}
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: vault-eso/app-default-values/vault/monitoring
  destination:
    name: {{ .Values.env }}
    namespace: {{ .Values.apps.vaultMonitoring.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
{{- end }}
