{{- if .Values.apps.vaultConfig.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-config-{{ .Values.env }}
  namespace: {{ .Values.argoCDNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.apps.vaultConfig.syncWave | quote }}
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: vault-eso/app-default-values/vault/manifests/{{ .Values.env }}
  destination:
    name: {{ .Values.env }}
    namespace: {{ .Values.apps.vaultConfig.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
