{{- if .Values.apps.vault.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-{{ .Values.env }}
  namespace: {{ .Values.argoCDNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.apps.vault.syncWave | quote }}
spec:
  project: default
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: {{ .Values.apps.vault.chartVersion | quote }}
      helm:
        valueFiles:
          - $values/vault-eso/vault/values/base.yaml
          - $values/vault-eso/argocd/environments/{{ .Values.env }}/vault/values.yaml
    - repoURL: {{ .Values.repoURL }}
      targetRevision: {{ .Values.targetRevision }}
      ref: values
  destination:
    name: {{ .Values.env }}
    namespace: {{ .Values.apps.vault.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
